# syntax=docker/dockerfile:1

FROM oven/bun:latest
# Set destination for COPY
WORKDIR /app

# Install git
RUN apt-get update && apt-get install -y git

COPY ./node_modules/@cloudflare/sandbox/container_src/* ./

RUN bun i https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz --no-save

EXPOSE 3000
# Run
CMD ["bun", "index.ts"]

